accounts/urls.py
from django.urls import path
from accounts import views
from accounts import views as accounts_view


app_name = 'accounts'

urlpatterns = [

    path('login', accounts_view.user_login, name='login'),
    path('logout', accounts_view.user_logout, name='logout'),
    path('register', accounts_view.user_register, name='register'),


    path('forgot-password', views.forgot_password, name='forgot-password'),
    path('confirm-email', views.confirm_email, name='confirm-email'),
    path('reset-password', views.reset_password, name='reset-password'),
    path('lock-screen', views.lock_screen, name='lock-screen'),

]

api/urls.py
from django.urls import path
from rest_framework_swagger.views import get_swagger_view

from .views import (
    AvaliacoesAPIView, AvaliacoesViewSet, CursoAPIView, 
    AvaliacaoAPIView, CursoViewSet, CursosAPIView, 
    UserAPIView, UsersAPIView
    )

from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'avaliacoes', AvaliacoesViewSet, basename='avaliacoes')
router.register(r'cursos', CursoViewSet, basename='cursos')

schema_view = get_swagger_view(title='Pastebin API')

urlpatterns = [
    # Rotas de Listagem
    path('cursos/', CursosAPIView.as_view(), name='cursos'),
    path('avaliacoes/', AvaliacoesAPIView.as_view(), name='avaliacoes'),
    path('usuarios/', UsersAPIView.as_view(), name='users'),

    # Rotas de Detalhes
    path('cursos/<int:pk>', CursoAPIView.as_view(), name='curso'),
    path('avaliacoes/<int:avaliacao_pk>', AvaliacaoAPIView.as_view(), name='avaliacao'),
    path('usuarios/<int:pk>', UserAPIView.as_view(), name='user'),

    # Rotas de Relacionamentos
    path('cursos/<int:curso_pk>/avaliacoes/', AvaliacoesAPIView.as_view(), name='curso_avaliacoes'),
    path('cursos/<int:curso_pk>/avaliacoes/<int:avaliacao_pk>', AvaliacaoAPIView.as_view(), name='curso_avaliacao'),
    path(r'^$', schema_view)
]

configurations/urls.py
from django.contrib import admin
from django.urls import path, include

from api.urls import router

urlpatterns = [
    path('', include('core.urls')),
    path('Contas/', include('accounts.urls')),
    path('api/v1/', include('api.urls')),
    path('api/v2/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('auth/', include('rest_framework.urls')),
]

core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.core_index, name='index'),
]

templates/partials/_footer.html
{% load static %} 
<footer class="footer">
    <div class="row g-0 justify-content-between fs--1 mt-4 mb-3">
        <div class="col-12 col-sm-auto text-center">
            <p class="mb-0 text-600">Powered by python and django  <span class="d-none d-sm-inline-block">| </span><br class="d-sm-none" /> 2021 &copy; <a href="https://themewagon.com/">Diretoria de Logística</a></p>
        </div>
        <div class="col-12 col-sm-auto text-center">
            <p class="mb-0 text-600">v.0.1.0</p>
        </div>
    </div>
</footer>

templates/partials/_header.html
   {% load static %} 
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>DL | Dashboard</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicons/favicon.ico' %}">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}">
    <meta name="msapplication-TileImage" content="{% static 'img/favicons/mstile-150x150.png' %}">
    <meta name="theme-color" content="#ffffff">
    <script src="{% static 'js/config.js' %}"></script>
    <script src="{% static 'vendors/overlayscrollbars/OverlayScrollbars.min.js' %}"></script>

    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="preconnect" href="https://fonts.gstatic.com/">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700%7cPoppins:300,400,500,600,700,800,900&amp;display=swap" rel="stylesheet">
    <link href="{% static 'vendors/overlayscrollbars/OverlayScrollbars.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/theme-rtl.min.css' %}" rel="stylesheet" id="style-rtl" disabled>
    <link href="{% static 'css/theme.min.css' %}" rel="stylesheet" id="style-default">
    <link href="{% static 'css/user-rtl.min.css' %}" rel="stylesheet" id="user-style-rtl" disabled>
    <link href="{% static 'css/user.min.css' %}" rel="stylesheet" id="user-style-default">
    <link href="{% static 'vendors/glightbox/glightbox.min.css' %}" rel="stylesheet" />
    
    <script>
      var isRTL = JSON.parse(localStorage.getItem('isRTL'));
      if (isRTL) {
        var linkDefault = document.getElementById('style-default');
        var userLinkDefault = document.getElementById('user-style-default');
        linkDefault.setAttribute('disabled', true);
        userLinkDefault.setAttribute('disabled', true);
        document.querySelector('html').setAttribute('dir', 'rtl');
      } else {
        var linkRTL = document.getElementById('style-rtl');
        var userLinkRTL = document.getElementById('user-style-rtl');
        linkRTL.setAttribute('disabled', true);
        userLinkRTL.setAttribute('disabled', true);
      }
    </script>

templates/partials/_navtop.html
   {% load static %} 
<nav class="navbar navbar-light navbar-glass navbar-top navbar-expand" style="display: none;">
    <button class="btn navbar-toggler-humburger-icon navbar-toggler me-1 me-sm-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarVerticalCollapse" aria-controls="navbarVerticalCollapse" aria-expanded="false" aria-label="Toggle Navigation"><span class="navbar-toggle-icon"><span class="toggle-line"></span></span></button>
    <a class="navbar-brand me-1 me-sm-3" href=" {% url 'core:index' %}">
        <div class="d-flex align-items-center"><img class="me-2" src="{% static '/img/logos/api.png' %}" alt="" width="30" /><span class="font-sans-serif text-primary">API</span></div>
    </a>

    <!-- NOTIFICAÇÕES -->
    <ul class="navbar-nav navbar-nav-icons ms-auto flex-row align-items-center">
        <li>
        <div class="form-check form-switch"><input class="form-check-input ms-0" id="mode-fluid" type="checkbox" data-theme-control="isFluid" /></div>
        </li>
        <li class="nav-item">
            <div class="theme-control-toggle fa-icon-wait px-2"><input class="form-check-input ms-0 theme-control-toggle-input" id="themeControlToggle" type="checkbox" data-theme-control="theme" value="dark" /><label class="mb-0 theme-control-toggle-label theme-control-toggle-light" for="themeControlToggle" data-bs-toggle="tooltip" data-bs-placement="left" title="Switch to light theme"><span class="fas fa-sun fs-0"></span></label><label class="mb-0 theme-control-toggle-label theme-control-toggle-dark" for="themeControlToggle" data-bs-toggle="tooltip" data-bs-placement="left" title="Switch to dark theme"><span class="fas fa-moon fs-0"></span></label></div>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link pe-0" id="navbarDropdownUser" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="avatar avatar-xl">
                    <img class="rounded-circle" src="{% static '/img/logos/ProfilePadrao.png' %}" alt="" />
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end py-0" aria-labelledby="navbarDropdownUser">
                <div class="bg-white dark__bg-1000 rounded-2 py-2">
                    <a class="dropdown-item fw-bold text-warning text-center"></span><span>Olá {{ request.user.first_name }}</span></a>
                    <div class="dropdown-divider"></div>
                    {% comment %} <a class="dropdown-item" href="#!">Set status</a> {% endcomment %}
                    {% comment %} <a class="dropdown-item" href="pages/user/profile.html">Meu Profile</a> {% endcomment %}
                    <a class="dropdown-item" href="#!">Feedback</a>
                    <div class="dropdown-divider"></div>
                    {% comment %} <a class="dropdown-item" href="pages/user/settings.html">Configurações</a> {% endcomment %}
                    <a class="dropdown-item" href=" {% url 'accounts:logout' %} ">Logout</a>
                </div>
            </div>
        </li>
    </ul>
    <!-- NOTIFICAÇÕES -->
    
</nav>                      
<script>
    var navbarPosition = localStorage.getItem('navbarPosition');
    var navbarVertical = document.querySelector('.navbar-vertical');
    var navbarTopVertical = document.querySelector('.content .navbar-top');
    var navbarTop = document.querySelector('[data-layout] .navbar-top');
    var navbarTopCombo = document.querySelector('.content [data-navbar-top="combo"]');
    if (navbarPosition === 'top') {
        navbarTop.removeAttribute('style');
        navbarTopVertical.remove(navbarTopVertical);
        navbarVertical.remove(navbarVertical);
        navbarTopCombo.remove(navbarTopCombo);
    } else if (navbarPosition === 'combo') {
        navbarVertical.removeAttribute('style');
        navbarTopCombo.removeAttribute('style');
        navbarTop.remove(navbarTop);
        navbarTopVertical.remove(navbarTopVertical);
    } else {
        navbarVertical.removeAttribute('style');
        navbarTopVertical.removeAttribute('style');
        navbarTop.remove(navbarTop);
        navbarTopCombo.remove(navbarTopCombo);
    }
</script>

templates/partials/_sidemenu.html
   {% load static %} 
<nav class="navbar navbar-light navbar-vertical navbar-expand-xl">
    <script>
        var navbarStyle = localStorage.getItem("navbarStyle");
        if (navbarStyle && navbarStyle !== 'transparent') {
            document.querySelector('.navbar-vertical').classList.add(`navbar-${navbarStyle}`);
        }
    </script>
    <div class="d-flex align-items-center">
        <div class="toggle-icon-wrapper">
            <button class="btn navbar-toggler-humburger-icon navbar-vertical-toggle" data-bs-toggle="tooltip" data-bs-placement="left" title="Toggle Navigation"><span class="navbar-toggle-icon"><span class="toggle-line"></span></span></button>
        </div>
        <a class="navbar-brand" href="index-2.html">
            <div class="d-flex align-items-center py-3"><img class="me-2" src="{% static 'img/logos/DL.png' %}" alt="" width="20" /><span class="font-sans-serif">DL</span></div>
        </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarVerticalCollapse">
        <div class="navbar-vertical-content scrollbar">
            <ul class="navbar-nav flex-column mb-3" id="navbarVerticalNav">
                <li class="nav-item">
                    <!-- parent pages-->
                    <a class="nav-link dropdown-indicator" href="#dashboard" role="button" data-bs-toggle="collapse" aria-expanded="true" aria-controls="dashboard">
                        <div class="d-flex align-items-center"><span class="nav-link-icon"><span class="fas fa-chart-pie"></span></span><span class="nav-link-text ps-1">Dashboard</span></div>
                    </a>
                    <ul class="nav collapse show" id="dashboard">
                        <li class="nav-item">
                            <a class="nav-link active" href="index-2.html" aria-expanded="false">
                                <div class="d-flex align-items-center"><span class="nav-link-text ps-1">Default</span></div>
                            </a>
                            <!-- more inner pages-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="dashboard/analytics.html" aria-expanded="false">
                                <div class="d-flex align-items-center"><span class="nav-link-text ps-1">Analytics</span></div>
                            </a>
                            <!-- more inner pages-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="dashboard/crm.html" aria-expanded="false">
                                <div class="d-flex align-items-center"><span class="nav-link-text ps-1">CRM</span></div>
                            </a>
                            <!-- more inner pages-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="dashboard/e-commerce.html" aria-expanded="false">
                                <div class="d-flex align-items-center"><span class="nav-link-text ps-1">E commerce</span></div>
                            </a>
                            <!-- more inner pages-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="dashboard/project-management.html" aria-expanded="false">
                                <div class="d-flex align-items-center"><span class="nav-link-text ps-1">Management</span></div>
                            </a>
                            <!-- more inner pages-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="dashboard/saas.html" aria-expanded="false">
                                <div class="d-flex align-items-center"><span class="nav-link-text ps-1">SaaS</span></div>
                            </a>
                            <!-- more inner pages-->
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav><nav class="navbar-top" style="display: none;"></nav>

templates/partials/js.html
{% load static %} 
<script src="{% static 'vendors/popper/popper.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/anchorjs/anchor.min.js' %}"></script>
<script src="{% static 'vendors/is/is.min.js' %}"></script>
<script src="{% static 'vendors/echarts/echarts.min.js' %}"></script>
<script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
<script src="{% static 'vendors/lodash/lodash.min.js' %}"></script>
<script src="{% static 'vendors/list.js/list.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<script src="{% static 'vendors/glightbox/glightbox.min.js' %}"></script>
<script src="https://unpkg.com/htmx.org@1.6.0"></script>
<script src="https://unpkg.com/htmx.org@1.6.0/dist/ext/client-side-templates.js"></script>
<script src="https://cdn.jsdelivr.net/npm/mustache@4.2.0/mustache.min.js"></script>