accounts/urls.py
from django.urls import path
from accounts import views
from accounts import views as accounts_view


app_name = 'accounts'

urlpatterns = [

    path('login', accounts_view.user_login, name='login'),
    path('logout', accounts_view.user_logout, name='logout'),
    path('register', accounts_view.user_register, name='register'),


    path('forgot-password', views.forgot_password, name='forgot-password'),
    path('confirm-email', views.confirm_email, name='confirm-email'),
    path('reset-password', views.reset_password, name='reset-password'),
    path('lock-screen', views.lock_screen, name='lock-screen'),

]

api/urls.py
from django.urls import path
from rest_framework_swagger.views import get_swagger_view

from .views import (
    AvaliacoesAPIView, AvaliacoesViewSet, CursoAPIView, 
    AvaliacaoAPIView, CursoViewSet, CursosAPIView, 
    UserAPIView, UsersAPIView
    )

from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'avaliacoes', AvaliacoesViewSet, basename='avaliacoes')
router.register(r'cursos', CursoViewSet, basename='cursos')

schema_view = get_swagger_view(title='Pastebin API')

urlpatterns = [
    # Rotas de Listagem
    path('cursos/', CursosAPIView.as_view(), name='cursos'),
    path('avaliacoes/', AvaliacoesAPIView.as_view(), name='avaliacoes'),
    path('usuarios/', UsersAPIView.as_view(), name='users'),

    # Rotas de Detalhes
    path('cursos/<int:pk>', CursoAPIView.as_view(), name='curso'),
    path('avaliacoes/<int:avaliacao_pk>', AvaliacaoAPIView.as_view(), name='avaliacao'),
    path('usuarios/<int:pk>', UserAPIView.as_view(), name='user'),

    # Rotas de Relacionamentos
    path('cursos/<int:curso_pk>/avaliacoes/', AvaliacoesAPIView.as_view(), name='curso_avaliacoes'),
    path('cursos/<int:curso_pk>/avaliacoes/<int:avaliacao_pk>', AvaliacaoAPIView.as_view(), name='curso_avaliacao'),
    path(r'^$', schema_view)
]

configurations/urls.py
from django.contrib import admin
from django.urls import path, include

from api.urls import router

urlpatterns = [
    path('', include('core.urls')),
    path('Contas/', include('accounts.urls')),
    path('api/v1/', include('api.urls')),
    path('api/v2/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('auth/', include('rest_framework.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields


class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        max_length=100,
        required=True,
        help_text='Digite um Email válido.',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Digite um Email Válido',

            })
    )


    first_name = forms.CharField(
        max_length=40,
        required=True,
        help_text='Digite seu Primeiro Nome.',
        widget=forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Seu Primeiro Nome',            
            })
    )

    last_name = forms.CharField(
        max_length=150,
        required=True,
        help_text='Digite o restante do nome.',
        widget=forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Complete o Nome',            
            })
    )

    username = forms.CharField(
        max_length=50,
        required=True,
        help_text='Escolha seu nome de Usuário.',
        widget=forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Este Nome de Usuário será usado para o Login',            
            })
    )

    password1 = forms.CharField(
        required=True,
        help_text='Digite uma senha.',
        widget=forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Digite uma Senha',            
            })
    )

    password2 = forms.CharField(
        required=True,
        help_text='Repita sua senha.',
        widget=forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'Repita a Senha',            
            })
    )

    checkterms = forms.BooleanField(
        required= True,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})
    )


    class Meta:
        model = User
        fields = [
            'email', 'first_name', 'last_name', 'username', 
            'password1', 'password2', 'checkterms', 
        ]


class UserAuthenticationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password')

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError('Erro - Verifique os dados') 

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.contrib import messages

from accounts.forms import RegisterForm, UserAuthenticationForm


def user_register(request):

    user = request.user
    if user.is_authenticated:
        return redirect('core:index')

    if request.method == 'GET':
        form = RegisterForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/register.html', context)

    if request.method == 'POST':
        form = RegisterForm(request.POST or None)

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(
                request,
                f'Olá {user}, Sua conta foi criada e você será '
                f'redirecionado para o seu Profile.'
            )
            return redirect('accounts:login')

        else:
            context = {
                'form': form
            }
        return render(request, 'accounts/register.html', context)
    return render(request, 'accounts/login.html', {})


def user_login(request, *args, **kwargs):
    context = {}
    # user recebe uma instancia do usuario
    user = request.user
    # se a requisição for POST
    if request.method == 'POST':
        # form vai receber os dados do HTML passados via POST
        form = UserAuthenticationForm(request.POST or None)
        # se o form for Válido, verificações do DJANGO
        if form.is_valid():
            # pega o email do form via POST
            username = request.POST['username']
            # pega o password do form via POST
            password = request.POST['password']
            # user vai receber a authenticação que o django fará com os dados
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                #
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect(destination)
                return redirect('core:index')
        else:
            context['login_form'] = form

    return render(request, 'accounts/login.html', context)


def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get('next'):
            redirect = str(request.GET.get('next'))
    return redirect


def user_logout(request):
    logout(request)
    return render(request, 'accounts/logout.html')


def forgot_password(request):
    return render(request, 'accounts/forgot-password.html')


def confirm_email(request):
    return render(request, 'accounts/confirm-email.html')


def reset_password(request):
    return render(request, 'accounts/reset-password.html')


def lock_screen(request):
    return render(request, 'accounts/lock-screen.html')

accounts/templates/accounts/confirm-email.html
{% extends 'baselogin.html' %}
{% load static %}
{% block baselogin %}


<div class="row min-vh-100 bg-100">
	<div class="col-6 d-none d-lg-block position-relative">
		<div class="bg-holder" style="background-image:url({% static 'img/generic/16.jpg' %});background-position: 50% 30%;"></div>
		<!--/.bg-holder-->
	</div>
	<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
		<div class="row justify-content-center g-0">
			<div class="col-lg-9 col-xl-8 col-xxl-6">
				<div class="card">
					<div class="card-header bg-circle-shape bg-shape text-center p-2"><a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" href="../../../index-2.html">falcon</a></div>
					<div class="card-body p-4">
						<div class="text-center">
							<img class="d-block mx-auto mb-4" src="{% static 'img/icons/spot-illustrations/16.png' %}" alt="Email" width="100">
							<h3 class="mb-2">Por favor verifique seu Email!</h3>
							<p>Um email foi enviado para <strong>xyz@abc.com</strong>. Por favor clique no link incluído no email para confirmar sua conta.</p>
							<a class="btn btn-primary btn-sm mt-3" href="login.html">
								<svg class="svg-inline--fa fa-chevron-left fa-w-10 me-1" data-fa-transform="shrink-4 down-1" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg="" style="transform-origin: 0.3125em 0.5625em;">
									<g transform="translate(160 256)">
										<g transform="translate(0, 32)  scale(0.75, 0.75)  rotate(0 0 0)">
											<path fill="currentColor" d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z" transform="translate(-160 -256)"></path>
										</g>
									</g>
								</svg>
								<!-- <span class="fas fa-chevron-left me-1" data-fa-transform="shrink-4 down-1"></span> Font Awesome fontawesome.com -->Retornar para Login
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock baselogin %}

accounts/templates/accounts/forgot-password.html
{% extends 'baselogin.html' %}
{% load static %}
{% block baselogin %}


<div class="container-fluid">
	<script>
		var isFluid = JSON.parse(localStorage.getItem('isFluid'));
		if (isFluid) {
		  var container = document.querySelector('[data-layout]');
		  container.classList.remove('container');
		  container.classList.add('container-fluid');
		}
	</script>
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder overlay" style="background-image:url({% static 'img/generic/17.jpg' %});background-position: 50% 76%;"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6">
					<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2"><a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" href="../../../index-2.html">MikeBook</a></div>
						<div class="card-body p-4">
							<div class="text-center">
								<h4 class="mb-0"> Esqueceu sua senha ?</h4>
								<small>Escreva seu email e nós enviaremos um link para resetar sua senha.</small>
								<form class="mb-3 mt-4">
									<input class="form-control" type="email" placeholder="Digite o email de cadastro">
									<div class="mb-3"></div>
									<button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Enviar link de reset</button>
								</form>
								<a class="fs--1 text-600" href="#!">Não conseguiu resetar a senha? entre em contato <span class="d-inline-block ms-1">→</span></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock baselogin %}

accounts/templates/accounts/lock-screen.html
{% extends 'baselogin.html' %}
{% load static %}
{% block baselogin %}


<div class="container-fluid">
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder" style="background-image:url({% static 'img/generic/18.jpg' %});"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6">
					<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2"><a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" href="../../../index-2.html">MikeBook</a></div>
						<div class="card-body p-4">
							<div class="row justify-content-center">
								<div class="col-auto">
									<div class="d-flex align-items-center">
										<div class="avatar avatar-4xl me-4">
											<img class="rounded-circle" src="{% static 'img/team/1.jpg ' %}" alt="">
										</div>
										<div class="flex-1">
											<h4>Hi! Emma</h4>
											<p class="mb-0">Digite sua senha <br>para voltar para o sistema.</p>
										</div>
									</div>
									<form class="mt-4 row gx-2">
										<div class="col"><input class="form-control" type="password" placeholder="Senha" aria-label="User's password" aria-describedby="user-password"></div>
										<div class="col-4"><button class="btn btn-primary d-block w-100" id="user-password" type="button">Login</button></div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock baselogin %}

accounts/templates/accounts/login.html
{% extends 'baselogin.html' %} 
{% load static %} 
{% block baselogin %} 


{% if user.is_authenticated %} 

<div class="container-fluid">
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder" style="background-image:url({% static 'img/generic/19.jpg' %});"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6">
					<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2"><a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" >MikeBook</a></div>
						<div class="card-body p-4">
							<div class="text-center">
								<img class="d-block mx-auto mb-4" src="{% static 'img/icons/spot-illustrations/45.png' %}" alt="shield" width="100">
								<h3>Você já está logado como</h3>
								<h2> {{ request.user.username }} </h2>
								<p> Deseja sair e entrar com outro Usuário? <br> Você será Desconectado.</p>
								<a class="btn btn-primary btn-sm mt-3" href=" {% url 'accounts:logout' %} ">
									<svg class="svg-inline--fa fa-chevron-left fa-w-10 me-1" data-fa-transform="shrink-4 down-1" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg="" style="transform-origin: 0.3125em 0.5625em;">
										<g transform="translate(160 256)">
											<g transform="translate(0, 32)  scale(0.75, 0.75)  rotate(0 0 0)">
												<path fill="currentColor" d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z" transform="translate(-160 -256)"></path>
											</g>
										</g>
									</svg>
									<!-- <span class="fas fa-chevron-left me-1" data-fa-transform="shrink-4 down-1"></span> Font Awesome fontawesome.com -->Desconectar
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% else %} 


<div class="container-fluid">
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder" style="background-image:url({% static 'img/generic/14.jpg' %});background-position: 50% 20%;"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6"> 

					{% if login_form.non_field_errors %}				
						<div class="text-center rounded text-light bg-danger">{{login_form.non_field_errors}}</div>
					{% endif %} 
					
				<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2">
							<a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light">MikeBook</a>
						</div>
						<div class="card-body p-4">
							<div class="row flex-between-center">
								<div class="col-auto">
									<h3>Login</h3>
								</div>
								<div class="col-auto fs--1 text-600">
									<span class="mb-0 fw-semi-bold">Ainda não é Membro? </span>
									<span>
										<a href={% url 'accounts:register' %}>Crie sua conta</a>
									</span>
								</div>
							</div>
							<form method="post"> 
							{% csrf_token %} 
							<div class="mb-3">
									<label class="form-label">Nome de Usuário</label>
									<input class="form-control" required="" name="username" type="text">
								</div>
								<div class="mb-3">
									<div class="d-flex justify-content-between">
										<label class="form-label" >Senha</label>
									</div>
									<input class="form-control" required="" name="password" type="password">
								</div>
								<div class="row flex-between-center">
									<div class="col-auto">
										<a class="fs--1" href=" {% url 'accounts:forgot-password' %} ">Esqueceu a senha?</a>
									</div>
								</div>
								<div class="mb-3">
									<button class="btn btn-primary d-block w-100 mt-3" type="submit" href=" {% url 'accounts:login' %} " name="submit">Log in</button>
								</div>
							</form>			
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div> 
{% endif %} 
{% endblock baselogin %}

accounts/templates/accounts/logout.html
{% extends 'baselogin.html' %}
{% load static %}
{% block baselogin %}


<div class="container-fluid">
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder" style="background-image:url({% static 'img/generic/19.jpg' %});"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6">
					<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2"><a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" >MikeBook</a></div>
						<div class="card-body p-4">
							<div class="text-center">
								<img class="d-block mx-auto mb-4" src="{% static 'img/icons/spot-illustrations/45.png' %}" alt="shield" width="100">
								<h3>Nos vemos depois!</h3>
								<p>Obrigado por usar o MikeBook </p><br><p class="text-danger" >Agora você está desconectado.</p>
								<a class="btn btn-primary btn-sm mt-3" href=" {% url 'accounts:login' %} ">
									<svg class="svg-inline--fa fa-chevron-left fa-w-10 me-1" data-fa-transform="shrink-4 down-1" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-left" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg="" style="transform-origin: 0.3125em 0.5625em;">
										<g transform="translate(160 256)">
											<g transform="translate(0, 32)  scale(0.75, 0.75)  rotate(0 0 0)">
												<path fill="currentColor" d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z" transform="translate(-160 -256)"></path>
											</g>
										</g>
									</svg>
									<!-- <span class="fas fa-chevron-left me-1" data-fa-transform="shrink-4 down-1"></span> Font Awesome fontawesome.com -->Voltar para o Login
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock baselogin %}

accounts/templates/accounts/register.html
{% extends 'baselogin.html' %} {% load static %} {% block baselogin %} <div class="container-fluid">
	</script>
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder" style="background-image:url({% static 'img/generic/19.jpg' %});"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6">
					<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2">
							<a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" >MikeBook</a>
						</div>
						<div class="card-body p-4">
							<div class="row flex-between-center">
								<div class="col-auto">
									<h3>Cadastrar</h3>
								</div>
								<div class="col-auto fs--1 text-600">
									<span class="mb-0 fw-semi-bold">Já é usuário?</span>
									<span>
										<a href=" {% url 'accounts:login' %} ">Login</a>
									</span>
								</div>
							</div>

							<form method="POST"> 
								{% csrf_token %}
								<div class="row">

									<div class="mb-3 col-sm-6">
										<label class="form-label">Primeiro Nome <label class="text-danger">*</label></label>
										{{ form.first_name }}
									</div>									
									{% if form.first_name.errors %}										
										{% for error in form.first_name.errors %}
											<ul>
												<li>{{ error|escape }}</li>
											</ul>
										{% endfor %}										
									{% endif %}

									<div class="mb-3 col-sm-6">
										<label class="form-label">Ultimo Nome <label class="text-danger">*</label></label>
										{{ form.last_name }}
									</div>
									{% if form.last_name.errors %}
										{% for error in form.last_name.errors %}
											<ul>
												<li>{{ error|escape }}</li>
											</ul>
										{% endfor %}
									{% endif %}

								</div>

								<div class="mb-3">
									<label class="form-label">Nome de Usuário <label class="text-danger">*</label></label>
									{{ form.username }}
								</div>
								{% if form.username.errors %}
									<label class="text-danger text-center">
									{% for error in form.username.errors %}
										<ul>
											<li>{{ error|escape }}</li>
										</ul>
									{% endfor %}
									</label>
								{% endif %}

								<div class="mb-3">
									<label class="form-label">Email <label class="text-danger">*</label></label>
									{{ form.email }}
								</div>
								{% if form.email.errors %}
									<label class="text-danger text-center">
										{% for error in form.email.errors %}
											<ul>
												<li>{{ error|escape }}</li>
											</ul>
										{% endfor %}
									</label>
								{% endif %}		

								<div class="row gx-2">

									<div class="mb-3 col-sm-6">
										<label class="form-label">Senha <label class="text-danger">*</label></label>
										{{ form.password1 }}
									</div>
									{% if form.password1.errors %}
										<label class="text-danger text-center">
											{% for error in form.password1.errors %}
												{{ error|escape }}
											{% endfor %}
										</label>									
									{% endif %}	

									<div class="mb-3 col-sm-6">
										<label class="form-label">Confirmação de senha <label class="text-danger">*</label></label>
										{{ form.password2 }}
									</div>
									{% if form.password2.errors %}
										<label class="text-danger">
											{% for error in form.password2.errors %}
												<ul>
													<li>{{ error|escape }}</li>
												</ul>
											{% endfor %}
										</label>
									{% endif %}	

								</div>	

								<div class="form-check">
									{{ form.checkterms }}
									<label class="form-label">Eu aceito os <a href="#!">termos </a>e as <a href="#!">politicas de privacidade</a>
									</label>
									{% if form.checkterms.errors %}
										{% for error in form.checkterms.errors %}
											{{ error|escape }}
										{% endfor %}
									{% endif %}

								</div>

								<div class="mb-3">
									<button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Enviar</button>
								</div>
							</form>


		
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div> {% endblock baselogin %}

accounts/templates/accounts/reset-password.html
{% extends 'baselogin.html' %}
{% load static %}
{% block baselogin %}


<div class="container-fluid">
	<div class="row min-vh-100 bg-100">
		<div class="col-6 d-none d-lg-block position-relative">
			<div class="bg-holder" style="background-image:url({% static 'img/generic/20.jpg' %});"></div>
			<!--/.bg-holder-->
		</div>
		<div class="col-sm-10 col-md-6 px-sm-0 align-self-center mx-auto py-5">
			<div class="row justify-content-center g-0">
				<div class="col-lg-9 col-xl-8 col-xxl-6">
					<div class="card">
						<div class="card-header bg-circle-shape bg-shape text-center p-2"><a class="font-sans-serif fw-bolder fs-4 z-index-1 position-relative link-light light" href="../../../index-2.html">MikeBook</a></div>
						<div class="card-body p-4">
							<h3 class="text-center">Resetar Senha</h3>
							<form class="mt-3">
								<div class="mb-3"><label class="form-label" for="split-reset-password">Nova Senha</label><input class="form-control" type="password" id="split-reset-password"></div>
								<div class="mb-3"><label class="form-label" for="split-reset-confirm-password">Confirmar Senha</label><input class="form-control" type="password" id="split-reset-confirm-password"></div>
								<button class="btn btn-primary d-block w-100 mt-3" type="submit" name="submit">Salvar e ir para Login</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock baselogin %}